<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tls.proto

namespace GPBMetadata;

class Tls
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\GrpcChat::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a09746c732e70726f746f1209677270635f6368617432370a0a54" .
            "6c735365727669636512290a0753656e644d7367120e2e677270635f6368" .
            "61742e4d73671a0e2e677270635f636861742e4d736742280a1a696f2e67" .
            "7270632e6578616d706c65732e677270635f636861744208477270634368" .
            "61745001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

