/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package designpatterns.weatherData;

import org.junit.Test;

public class WeatherDataTest {
    @Test public void testObserver() {
        WeatherData wd = new WeatherData();

        Observer l = new Logger();
        Observer d = new Display();
        wd.registerObserver(l);
        wd.registerObserver(d);
        wd.setTemperature(1.0f);
        wd.setHumidity(2.00f);
    }
}
