/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesignPatterns.Duck;

import DesignPatterns.Duck.Duck;
import DesignPatterns.Duck.FakeDuck;
import DesignPatterns.Duck.FlyNoWay;
import DesignPatterns.Duck.NormalDuck;
import org.junit.Test;
import static org.junit.Assert.*;

public class DuckTest {
    @Test public void testFakeDuck() {
        Duck duck = new FakeDuck();
        duck.performFly();
        duck = new NormalDuck();
        duck.performFly();
    }
}
