[package]
name = "guessing_game_xiaochai"
version = "0.1.1"
authors = ["xiaochai<soso2501@gmail.com>"]
edition = "2018"
description = "a game demo"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"