<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_chat.proto

namespace Grpc_chat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc_chat.Count</code>
 */
class Count extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     */
    private $count = 0;
    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     */
    private $offset = 0;

    public function __construct() {
        \GPBMetadata\GrpcChat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

}

