<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_chat.proto

namespace Grpc_chat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc_chat.Msg</code>
 */
class Msg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender = 1;</code>
     */
    private $sender = '';
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    private $msg = '';

    public function __construct() {
        \GPBMetadata\GrpcChat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string sender = 1;</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>string sender = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

