<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_chat.proto

namespace Grpc_chat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc_chat.Names</code>
 */
class Names extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     */
    private $firstName = '';
    /**
     * Generated from protobuf field <code>string secondName = 2;</code>
     */
    private $secondName = '';

    public function __construct() {
        \GPBMetadata\GrpcChat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secondName = 2;</code>
     * @return string
     */
    public function getSecondName()
    {
        return $this->secondName;
    }

    /**
     * Generated from protobuf field <code>string secondName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSecondName($var)
    {
        GPBUtil::checkString($var, True);
        $this->secondName = $var;

        return $this;
    }

}

